module.exports = {
    USER_COLLECTION : "users" ,
    ADMIN_COLLECTION : "admin" , 
    ADMIN_CATEGORY_COLLECTION : "book_category" ,
    ADMIN_SUB_CATEGORY_COLLECTION : "book_sub_category"  ,
    ADMIN_BOOK_COLLECTION : "books" ,
    WISHLIST_COLLECTION : "wishlist" ,
    CART_COLLECTION : "cart" ,
    ADD_DELIVERY_RATE : "shipping_rate",
    FIRST_BANNER_DATA : "first_banner" ,
    SECOND_BANNER_DATA : "second_banner"  ,
    AUTHOR_BANNER_DATA : "author_banner" ,
    PROMOTION_BANNER_DATA : "promotion_banner" ,
    LAST_PROMOTION_BANNER_DATA : "last_promotion_banner" ,
    COUPON_BANNER_DATA : "coupon_banner" , 
    USER_ADDRESS_DATA : "user_address" ,
    ORDER_COLLECTION : "order" ,
    ADMIN_DP_COLLECTION : "admin_dp",
    SUBSCRIPTION_PLANS : "plans" ,
    SUBSCRIPTION_PAID_COLLECTION : "paid_plan" ,
    COUPON_COLLECTION : "coupon" ,
    RETURN_BOOK : "return" ,
    FINE_AMOUNT_USERS : "fineUsers" ,
    TOTAL_SUBSCRIPTION_PAID_COLLECTION : "total_paid_plan"
}